name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

# Allow parallel jobs on `main` to test each commit. For PRs, only run on the latest commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    name: Grammar Tests

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npm run log:versions

      - run: npm run build
      # TODO: Abort if there are diffs; see #18
      - name: Ensure generated files are up-to-date
        run: |
          # package.json may change due to custom scripts
          git checkout HEAD -- package.json

          git diff --diff-filter=M --color | head -n 100
          git diff --diff-filter=M --quiet || (echo 'Generated grammar is not up-to-date: run `npm run build` and commit all changes')
          git reset --hard HEAD

      - run: npm run test:all
      - run: npm run lint

      - name: test rust bindings
        run: |
          cargo build --verbose
          cargo test --verbose

      - name: test node bindings
        run: |
          cd test/bindings/node
          npm ci
          npm test
